### PR TITLE
adding project namespace to image name

### PR DESCRIPTION
**Pull request by ThomasQuinnKelly**

### CODE REVIEW

**Comment by abhijitvk** [comment]
@ThomasQuinnKelly who is reviewing this? 

Was this based on someone requesting changes? Won't we  need to do similar changes in reference person and communicate it to other teams?

**Comment by ThomasQuinnKelly** [comment]
https://vajira.max.gov/browse/AF-697

Is the connected user story 

https://github.com/department-of-veterans-affairs/bip-reference-person/pull/135

is the similar pull request in reference person 

Yes we would have to communicate it to other teams as well

**Comment by ThomasQuinnKelly** [comment]
I had sent these over to Max and he is having me test something else

**Comment by abhijitvk** [comment]
Is this still being tested?

**Comment by ThomasQuinnKelly** [comment]
Yes - Max has requested full testing on this change -

**Pull request merged**
